export const todolist = [
  {
    id: 1,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: true,
    createDate: "2022.09.02",
    completeDate: "2022.09.04",
  },
  {
    id: 2,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: true,
    createDate: "2022.09.02",
    completeDate: "2022.09.04",
  },
  {
    id: 3,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
  {
    id: 4,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
  {
    id: 5,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
  {
    id: 6,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
  {
    id: 7,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
  {
    id: 8,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
  {
    id: 9,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
  {
    id: 10,
    title: "장보러가기",
    contents: "꼭 가야된다...",
    tags: [
      { name: "사과", color: "" },
      { name: "간장", color: "" },
      { name: "미림", color: "" },
    ],
    complete: false,
    createDate: "2022.09.02",
    completeDate: "",
  },
];
